<a href="https://colab.research.google.com/github/Kiran-Shehzadi/flyrank-ML_Internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Kiran-Shehzadi/flyrank-ML_Internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

## My Lane as an ML Task

My selected lane is **Content Refresh Prioritization**.

The business goal is to help the SEO team identify which webpages should be refreshed first in order to improve search performance.

I frame this as a **scoring (regression)** problem. Instead of making a simple Yes/No decision, the model assigns each webpage a **refresh priority score**. Pages with higher scores are expected to benefit more from a content update.

The SEO team can then rank pages using these scores and prioritize the highest-value pages for refresh.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

## Target or Proxy

The starter dataset does not contain the actual improvement in traffic after refreshing a page, so a direct target is unavailable.

Instead, I would create a **proxy target** called **Refresh Priority Score**.

This score estimates how urgently a page should be refreshed based on signals such as:

- Click-through Rate (CTR)
- Average Position
- Content Age
- Trend Direction
- Impressions

# Higher scores indicate higher refresh priority.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

## Success Metric

The success of this ML system would ultimately be measured by business outcomes after refreshing the recommended pages.

Important success metrics include:

- Increase in organic clicks
- Improvement in CTR
- Better average search ranking
- Growth in impressions
- Increase in organic traffic

# If this were developed into a regression model, evaluation metrics such as **Mean Absolute Error (MAE)** or **Root Mean Squared Error (RMSE)** could also be used.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [3]:
!git clone https://github.com/Kiran-Shehzadi/flyrank-ML_Internship.git

Cloning into 'flyrank-ML_Internship'...
remote: Enumerating objects: 137, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 137 (delta 47), reused 99 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (137/137), 1.84 MiB | 4.51 MiB/s, done.
Resolving deltas: 100% (47/47), done.

In [4]:
%cd flyrank-ML_Internship

/content/flyrank-ML_Internship

In [5]:
!ls data/raw

content_refresh_anonymized.csv

In [7]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [13]:
df.shape

(30000, 45)

In [10]:
df.columns

Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count', 'provider_used', 'model_used', 'impressions_90d',
       'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d',
       'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d',
       'days_with_impressions', 'days_with_sessions', 'impressions_last_30d',
       'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d',
       'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier',
       'age_tier_order', 'days_since_last_update', 'freshness_tier',
       'word_count_tier', 'char_count_tier', 'ctr', 'avg_position',
       'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'],
      dtype='object')

In [11]:
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## Unit of Analysis

The unit of analysis is **one webpage**.

Each row in the dataset represents a single webpage, while each column contains information describing that page, such as:

- Click-through Rate (CTR)
- Impressions
- Average Position
- Content Age
- Trend Direction

These features help determine whether a webpage should be refreshed.

In [12]:
df["refresh_priority_score"] = (
    (1 - df["ctr"]) * 0.4 +
    (df["content_age_days"] / df["content_age_days"].max()) * 0.3 +
    (df["avg_position"] / df["avg_position"].max()) * 0.3
)

df[[
    "ctr",
    "content_age_days",
    "avg_position",
    "refresh_priority_score"
]].head()

    ctr  content_age_days  avg_position  refresh_priority_score
0  0.76               187          10.6                0.208448
1  0.05               445          20.3                0.641559
2  0.09               141          36.5                0.483694
3  0.49               463           6.2                0.457868
4  0.13               263          44.0                0.541771

The **refresh_priority_score** shown above is an example proxy target.

It combines several important signals to estimate which webpages should be refreshed first.

This score is only a demonstration for task framing and is **not** a trained machine learning prediction.

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

## Why ML Beats a Fixed Rule

A fixed rule, such as "refresh every page older than 180 days," ignores many other important factors.

For example:

- An old page may still perform very well.
- A newer page may already be losing traffic.
- Two pages with the same CTR may have very different search positions or impression counts.

Machine learning can evaluate multiple signals together, including CTR, average position, content age, impressions, and trend direction.

By learning patterns across these features, an ML model can produce better refresh recommendations than a single threshold-based rule.

## Self-check

Before you submit, confirm each line honestly:

- [YES] Every section above is filled — markdown thinking AND the code that backs it
- [YES] The notebook runs top to bottom with no errors (Runtime → Run all)
- [YES] No client names, URLs, or private queries anywhere
- [YES] My claims use careful words: observed, measured, directional, decision-support
- [YES] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.